### ISSUE TITLE
Twig config not being applied upon updating to 0.11.0

### ISSUE THREAD

**Issue by VesterDe** [htmlburger/wpemerge#9] opened 2018-11-16 17:50 UTC
## Version

_Please add the exact versions used for each of the following:_

  - WP Emerge: 0.11.0
  - WordPress: 4.9.8
  - PHP: 7.2

## Expected behavior

Twig config passed to WPEmerge::boot should work, for example allowing me to pass a 'views' parameter to specify where my twig views are.

## Actual behavior

Twig config never makes it to the view engine, no options are applied.

## Steps to reproduce (in case of a bug)

  1. Use wpemerge-twig, pass twig config options to boot().
  2. Twig config options are not applied to the twig view engine (try turning debug on/off etc...)

## Comments

This worked up to 0.10.0, now I'm I've updated to 0.11.0.

My twig loader started throwing template not found errors. I've investigated a bit, and it's because my twig config is not loaded properly from the array I pass to boot.

More specifically, it seems WPEmerge\Support\Arr@get is always defaulting (line 240), where it's being used by trait WPEmerge\ServiceProviders\ExtendsConfigTrait@extendconfig to parse the options from the container.

**Comment by atanas-angelov-dev** [comment] 2018-11-16 17:56
Hi @VesterDe ,

Could you please paste your full ::boot() call with the supplied config?

**Comment by VesterDe** [comment] 2018-11-16 18:04
Sure:

`WPEmerge::boot([
    'providers' => [
        App\View\ServiceProvider::class,
        App\External\Slack\ServiceProvider::class,
        App\External\Freshsales\ServiceProvider::class,
        App\External\Drip\ServiceProvider::class,
        \WPEmergeTwig\View\ServiceProvider::class,
    ],
    'twig' => [
        'replace_default_engine' => false,
        'views' => APP_THEME_ROOT . '/templates/twig/',
        'options' => [
            'debug' => env('WP_ENV') !== 'production'
        ]
    ],
    'global_middleware' => [
        App\Middleware\CacheDeleteMiddleware::class
    ],
]);`

**Comment by VesterDe** [comment] 2018-11-16 18:04
Sure,

WPEmerge::boot([
    'providers' => [
        App\View\ServiceProvider::class,
        App\External\Slack\ServiceProvider::class,
        App\External\Freshsales\ServiceProvider::class,
        App\External\Drip\ServiceProvider::class,
        \WPEmergeTwig\View\ServiceProvider::class,
    ],
    'twig' => [
        'replace_default_engine' => false,
        'views' => APP_THEME_ROOT . '/templates/twig/',
        'options' => [
            'debug' => env('WP_ENV') !== 'production'
        ]
    ],
    'global_middleware' => [
        App\Middleware\CacheDeleteMiddleware::class
    ],
]);

**Comment by atanas-angelov-dev** [comment] 2018-11-16 21:31
Confirmed and fixed in `master`. The Twig service provider incorrectly overrides your config.

Here's a workaround until the next version is shipped - we define another service provider and add it immediately after the Twig one so it overrides it:

`app/config.php`
```php
// ...
'providers'         => [
	// ...
	\WPEmergeTwig\View\ServiceProvider::class,
	\App\TwigConfigWorkaroundServiceProvider::class,
	// ...
],
// ...
```

`app/src/TwigConfigWorkaroundServiceProvider.php`
```php
<?php

namespace App;

use WPEmerge\ServiceProviders\ServiceProviderInterface;

/**
 * Workaround for htmlburger/wpemerge#9.
 *
 * This class should be removed and the config should be
 * moved back to config.php once WP Emerge 0.11.1 is
 * released.
 *
 * @link https://github.com/htmlburger/wpemerge/issues/9.
 */
class TwigConfigWorkaroundServiceProvider implements ServiceProviderInterface {
	/**
	 * {@inheritDoc}
	 */
	public function register( $container ) {
		$container[ WPEMERGE_CONFIG_KEY ] = array_replace_recursive(
			$container[ WPEMERGE_CONFIG_KEY ],
			[
				'twig' => [
					// Your config goes here:
					'replace_default_engine' => false,
					'views' => APP_THEME_ROOT . '/templates/twig/',
					'options' => [
						'debug' => env('WP_ENV') !== 'production'
					]
				],
			]
		);
	}

	/**
	 * {@inheritDoc}
	 */
	public function boot( $container ) {
		// nothing to boot
	}
}
```


PS:
I assume `APP_THEME_ROOT` is defined in your project since it is not defined in the starter theme.

**Comment by VesterDe** [comment] 2018-11-19 14:20
Thanks!

Yes, you assume correctly.

**Closed** 2018-11-19 22:38 UTC
Labels: bug
